import "./globals.css";
import { random, cachedRandom } from "@/lib/random";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const r1 = random();
  const r2 = cachedRandom();

  return (
    <html lang="en">
      <body>
        <main>
          <h1>Layout</h1>
          <div>random: <pre>{r1}</pre></div>
          <div>random(cached): <pre>{r2}</pre></div>
          {children}
        </main>
      </body>
    </html>
  )
}
